### ISSUE TITLE
Set up a DRF /resources endpoint

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#1]
Guide: https://www.django-rest-framework.org/tutorial/quickstart/

**Comment by lpatmo** [comment]
Both @BethanyG and @brylie picked up on this -- will schedule a hangout to sort out the different patterns.

**Comment by brylie** [comment]
I will defer to @BethanyG here, but am exited to help with peer review and other coding tasks :-)

**Comment by BethanyG** [comment]
Closing this in favor of issues  #19 , #20 , & #21.  The read endpoint is done.
