### ISSUE TITLE
Use Pipenv for dependency management

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#11]
It may be helpful to use Pipenv rather than just `pip` for dependency management. This is namely because project dependency updating is made simpler by Pipenv, along with a few other niceties like automatically initializing environment variables when activating the virtual environment.

**Comment by BethanyG** [comment]
Since we will have programmers that will be using `conda`, `virtualenv`, `venv`, and many others , I don't think we want to force any of them to use `pipenv` over what they may already be accustom to.  I'd rather have a "lowest common denominator" that anyone can then adapt to their preferred env management style.  @lpatmo  -- thoughts on this?

**Comment by lpatmo** [comment]
Is there any way to make `pipenv` optional, or does its presence in the codebase necessitate a particular configuration setup when someone forks the repo and tries to set up their dev environment for the first time?

I'm a little hesitant to commit to pipenv based on what I'm reading at https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/, and generally agree with Bethany that having a "lowest common denominator" setup is better, but I'm open to counter-arguments.

**Comment by brylie** [comment]
Pipenv uses pip underneath, and we can still maintain a requirements.txt. So, in that regard it is less disruptive than, say, conda.

**Comment by brylie** [comment]
Pipenv uses pip underneath, and we can keep `requirements.txt` around for lowest common denominator use cases. Pipenv just [gives us a helping hand in a few ways](https://github.com/pypa/pipenv#-features), like clean dependency management, automatically activating environment variables, and simpler semantics for environment setup.

There will always be detractors, and the same Google search can likely turn up articles supporting Pipenv as part of a supportive developer experience.

https://opensource.com/article/18/2/why-python-devs-should-use-pipenv
https://realpython.com/pipenv-guide/#is-pipenv-worth-checking-out
https://able.bio/SamDev14/pipenv-whats-all-the-buzz-about--141lx34
https://towardsdatascience.com/comparing-python-virtual-environment-tools-9a6543643a44
https://packaging.python.org/guides/tool-recommendations/

**Comment by BethanyG** [comment]
I have no problem with `pipenv`, should someone want to use it.  I do, however have a problem with it being required for development and being an additional set of files to keep updated.   Many developers use conda/Anaconda (I do - among other tools).  Many also use docker and no `venvs` at all.  How a contributor reproduces the env should not be an issue or a roadblock.  I also would have a problem with having to support / train contributors unfamiliar.

**Comment by brylie** [comment]
It is not the intention of this issue to start a flame war nor limit developer freedom, and we are certainly free to disregard this request (no worries :smile:). 

That said, it is also worth considering that having [one, obvious way](https://www.python.org/dev/peps/pep-0020/), meaning clearly documented, to set-up a development environment can be liberating, particularly for new developers. By way of example, at both [Apinf](https://github.com/apinf/platform) and [CiviWiki](https://github.com/CiviWiki/OpenCiviWiki) projects, we had several cases where new, potential contributors were stymied by the ambiguity and choices involved in simply creating a development environment.

The recommendation here for Pipenv is not my own, but is also the [recommended way to manage Python application dependencies](https://packaging.python.org/guides/tool-recommendations/#application-dependency-management) by the Python Packaging Authority. Pipenv is not perfect (or without debate), but really does offer many benefits and simplicity to the Python application developer workflow.

Kind regards,
Brylie

**Comment by lpatmo** [comment]
Thanks @brylie and @BethanyG for your input! This is tough, since I agree with points both of you have made. :) In particular:

> worth considering that having one, obvious way, meaning clearly documented, to set-up a development environment can be liberating, particularly for new developers stymied by the ambiguity and choices involved in simply creating a development environment.

> have a problem with it being required for development and being an additional set of files to keep updated.

At the moment, it seems like whether we use it or not isn't an urgent matter. Can we give it some time to think about it some more (also for me to familiarize myself better with the benefits of making it standard)?

In terms of django-exploration, also feel like this question doesn't need to get decided right away.

**Comment by bengineerdavis** [comment]
There are some serious [reliability issues](https://github.com/pypa/pipenv/issues/4070) and [readability](https://pipenv-fork.readthedocs.io/en/latest/basics.html#example-pipfile-lock) issues with pipenv. Specifically, the massive amount of open issues within the forked project by PyPA:

[331 open issues as of this post](https://github.com/pypa/pipenv/issues)

Specifically, that there is a concensus that while there is earnest effort, the team is (by their own admission, under-staffed:
[If this project is dead, just tell us](https://github.com/pypa/pipenv/issues/4058) 

I humbly, but strongly, encourage us to stick with pip and venv to maintain this project for the long-term until the newer version come out and has had some tests by the user community in the field.

**Comment by bengineerdavis** [comment]
I have recently--thanks to the recommendation of some of our community members--had great success with [pip-compile-multi](https://github.com/peterdemin/pip-compile-multi) in some of my personal projects. This is an abstraction on top of [pip-tools](https://github.com/jazzband/pip-tools), another dependency tool that helps to self-document dependencies is a much more readable way, and keeps closer in line with the [Zen of Python](https://www.python.org/dev/peps/pep-0020/). Thanks for your time.

**Comment by brylie** [comment]
Closing as "wontfix" :-)
