### ISSUE TITLE
Add instructions for setting up postgres locally (for new contributors)

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#12]
Some of my notes from when I set it up locally (with @BethanyG's help):

```
- Set up postgres: https://wiki.postgresql.org/wiki/First_steps
- https://gist.github.com/ibraheem4/ce5ccd3e4d7a65589ce84f2a3b7c23a3
- createuser --interactive --pwprompt
- createdb cbv3
```

I'll need to double check exactly what I did. Luckily I still have the recording of it!

**Comment by brylie** [comment]
By the way, are we publishing codebuddies related hangouts on a particilsr channel or keyword tag? It would be cool to see all the Codebuddies content somehow related.

I am live-streaming on Twitch then uploading to YouTube, and can add a Codebuddies tag to the uploads. It would also be good to know how to use Twitch for Codebuddies hangouts.

**Comment by lpatmo** [comment]
I've been forwarding Twitch streams on twitch.tv/codebuddies over to CodeBuddies' YouTube channel on https://www.youtube.com/channel/UCOBp46r9_g8kKRCc0y-rJVg. 

> I am live-streaming on Twitch then uploading to YouTube, and can add a Codebuddies tag to the uploads. 

That sounds great, thanks! I'm not entirely sure how to search on Twitch by tag -- e.g. if I type "codebuddies" here it only brings up my videos from twitch.tv/codebuddies, not yours that you've tagged #codebuddies. 

![image](https://user-images.githubusercontent.com/4512699/65380206-30467700-dc8b-11e9-95e6-9663590d47ff.png)

Let me know if there are other features you'd like me to make use of -- e.g. adding you as a collaborator on Twitch, or "raiding" your channel, etc. I'm still new to Twitch features.

**Comment by BethanyG** [comment]
Some additional links:

**Postgres in Docker**:  https://hackernoon.com/dont-install-postgres-docker-pull-postgres-bee20e200198

**Postgres How-Tos**: http://postgresguide.com/setup/install.html

**Comment by BethanyG** [comment]
again, attempting to consolodate setup issues in one place.  Please see issue #3
