### ISSUE TITLE
Provide Documentation on Managing Secrets Through ENV Vars for Django

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/django-concept#13]
We need to provide documentation for new users on how to manage things like DB connection information and passwords through ENV variables, since the next version of the prototype will have them.

**Comment by brylie** [comment]
This is one place where Pipenv tool and .env file would streamline the process. E.g. we can provide a `.env.example` that the developer can modify and save as `.env`.

**Comment by BethanyG** [comment]
It could, but for developers that don't use `pipenv`, we'll need a more general rundown.

**Comment by BethanyG** [comment]
Closing this in favor of consolidating setup issues in one place.    Please see issue #3 .
