### ISSUE TITLE
Set up JWT authorization & tests.

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/django-concept#18]
Set up JWT authorization on the DRF backend & test to make sure it's implemented correctly.  This includes:

- [X]  Installing the necessary components & updating the `requirements.txt` file.
- [X]  Changing `base.py` settings to add DRF permission classes, CORS origin whitelist entries, and JWT_AUTH parameters.
- [X]   Creating a `auth` endpoint for requesting JWT tokens with a username and PW
- [X]  Creating new `userauth` app for user authorization, with `current_user` and `UserList` views.
- [X]  Adding new routes to support signup, auth, and authorized users
- [X]  Adding new serializers for decoding JWTs and for requesting a JWT on registration
- [X]  Adding new JWT response handler in `utils.py`
- [X]  Adding an appropriate `auth` views for returning user info based on their JWT, and for returning a JWT from a new user registration.
- [x]   **Adding appropriate tests to verify the new feature additions**

**Comment by BethanyG** [comment]
Currently coded in (https://github.com/BethanyG/django-concept/tree/issue-18) but missing tests, so I'm not going to do a pull request until those are complete.

**Comment by lpatmo** [comment]
Update: the latest is in https://github.com/BethanyG/django-concept/tree/issue-24

**Comment by BethanyG** [comment]
Can we close this now that it has been merged, or are there issues we'd like to hold it open for?

**Comment by lpatmo** [comment]
Yes, let's close this! (Thanks for being on top of it)
