### ISSUE TITLE
Set up a page using React

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#2]

**Comment by brylie** [comment]
Not to start a :fire: war, but could we please maybe discuss the *possibility* of using Vue for this project?

**Comment by lpatmo** [comment]
@brylie Yes, I will create a new repo specifically for Vue exploration! (I don't have that background, but others might want to explore/share)

**Comment by lpatmo** [comment]
(Going to close this -- as a React app at https://github.com/codebuddies/react-concept will be feeding from the API endpoints created by this Django app)
