### ISSUE TITLE
[API] Endpoint for deleting a resource

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#21]
We need to create a `/resources/{resource_id}` endpoint that accepts the following body:

{
      "id": "7e08e0b0-da77-11e9-95c3-d20089b01401"
}

Making a DELETE request to resources/{resource_id} should result in the resource being deleted.

**Comment by BethanyG** [comment]
@zashary -- if you fork https://github.com/BethanyG/django-concept/tree/issue-20, it should have all the changes to get you started.  Recommend Postman (https://www.getpostman.com/), postwoman (https://postwoman.io/), or if you like the command line cURL for testing.

**Comment by BethanyG** [comment]
This fixed by the PR above - apologies - once the endpoint was set up correctly, DELETE was automagically supported.
