### ISSUE TITLE
Rename model fields

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#24]
Formerly named:
- credit, referrer

Add:
```
    # specific URL of resource
    url = models.URLField(max_length=300)

    # the URL of the referring/source site.  e.g. URL of tweet, if it was tweeted.
    referring_url = models.URLField(blank=True, max_length=300)

    # names of persons who suggest this resource to the user
    referring_user = models.CharField(max_length=100)
```

**Comment by BethanyG** [comment]
Quick question/clarification on this.   is `referring_user` a second codebuddies user in our system, or just a person who may have suggested the resource to the user **entering** the resource in the system?    The reason I ask is because if it is an additional codebuddies user, we should model this as a second foreign key into the users table, and not leave `referring_user` as a text field.  And if it is like the comment says a _person_ who suggested the resource, but not necessarily a codebuddies user, I think we may want to name that field `referring_name` or `referring_person`.

**Comment by BethanyG** [comment]
Just for complete context, this is the full `Resource` Record:

```
{
      "model":"resources.resource",
      "pk":"02ef2aaa-da96-11e9-8a1f-d20089b01401",
      "fields":{
         "title":"The Life of a File (in Elm)",
         "author":"Evan Czaplicki",
         "description":"Elm Europe 2017 -- Evan Czaplicki, the life of a file",
         "url":"https://www.youtube.com/watch?v=XpDsk374LDE",
         "referring_url":"https://www.youtube.com/watch?v=kEitFAY7Gc8",
         "referring_user":"Gina Aspey (gaspeyl@unicef.org)",
         "user":10,
         "date_published":"2019-09-19T04:29:04Z",
         "created":"2019-09-19T04:29:04.069Z",
         "modified":"2019-09-19T04:29:04Z",
         "media_type":"TALK",
         "paid":true,
         "tags":[
            {
               "id":"44929775-9bb4-4840-af64-c6b0649d6677",
               "name":"Elm"
            },
            {
               "id":"0d325a30-7262-4914-90fe-6c90ac725fc2",
               "name":"FrontEnd"
            },
            {
               "id":"a1167632-abb8-4ce1-b090-b84e79c94c7f",
               "name":"JavaScript"
            }
         ]
      }
```

**Comment by angelocordon** [comment]
Is the user and the referring_user the same
thing in this case?

**Comment by BethanyG** [comment]
That's what I need clarity on.

**Comment by angelocordon** [comment]
IMO, then yes I agree with your initial thoughts of removing the field. I’m not sure why we’d need a second user; I’m inclined to say that one can’t share a resource without being a cb user, if that makes sense.

**Comment by BethanyG** [comment]
totally.  I just don't know if it's also desirable to have a field that gives credit to whomever told the cb user about the resource in the first place.  That was the original name of that feild:  credit.  But credit is a confusing name, so referring_user was an attempt to clarify it   (I think).

**Comment by lpatmo** [comment]
Ah yeah, referring_source might be a better name. It shouldn't be a user
id. It's whoever (or whatever) you want to give credit to for that
resource, but user is the one submitting the resource. Thanks for flagging!

**Comment by BethanyG** [comment]
ok.  named it `other_referring_source`.  Will commit it to the `issue-24` branch.

**Comment by lpatmo** [comment]
Thanks!

**Comment by billglover** [comment]
When I originally mocked the `Resource` my intent was to use referred to capture how I found out about the resource; a link to a tweet, the url of a blog post or comment, the twitter handle of a person.

The reason I thought this helpful is that I often get round to reading or watching resources weeks or months after I found them and if they are useful I like to share with others and thank or give credit to the person who passed them to me.

I also hoped to use it to explore themes in where or how I was finding my most useful resources.

**Comment by lpatmo** [comment]
Yes, that makes a lot of sense. And ++ why it should be a string and not refer to a user ID.

**Comment by BethanyG** [comment]
So I think keeping both the `referring_url` (which goes through a URL validator) and `other_referring_source` (which is a text field that can hold anything) sounds good to me.  

That way, if the referrer is a URL - we have it, and if the user feels like they should be crediting something else (like a conference or meetup talk or covo with someone) - they have the flexibility to do so with the `other_referring_source` field.  And we can also name these in a more context-appropriate way on the webiste, as long as everyone's clear on what they map to.

**Comment by lpatmo** [comment]
Sounds good to me too! Thanks for starting the convo to clarify.

**Comment by BethanyG** [comment]
Pulled these changes back into my for before starting the tests, so they are included in the pull request.

**Comment by BethanyG** [comment]
Going to close this as completed for this context.
