### ISSUE TITLE
UUID for Tags??

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/django-concept#25]
Putting this here for discussion.  As currently modeled, our Resources have a JSON field with tags that have a UUID and a text string.  We may decide to change this, but for now that is the model.  The current UUIDs are below.  Should we continue in this pattern, or should we not assign UUIDs to tags?

UUID | Tag Name
-- | --
20fba58a-2702-4378-b0f9-5ac0193d4965 | Django
32cd4ddc-6a8e-48b2-be60-45de1784e5c7 | Python
f81f08af-6bdd-465f-8aba-1693e7348f7d | REST
d4ab862d-1746-4cd3-a91a-a861e2a6c5a1 | Go
a1167632-abb8-4ce1-b090-b84e79c94c7f | JavaScript
66cc3539-6705-45ee-b15d-644d5fb90c41 | ES6
c265a4fe-d03f-445d-805f-477e05d9f4cb | Node
e7891e62-8934-486e-8085-09f557bf06f6 | HTML5
f9be333e-37c7-4eb1-9b0a-44bd782dab9f | CSS
eab9af24-7e12-440c-bf81-48a8646b6825 | LESS
7a544998-cc89-4f25-8010-be7012a615d6 | SASS
446bd3dd-2190-4747-8a43-fcb0455ae660 | Vue
c368c671-4083-4d2d-b4e7-2047a889249d | Java
8b99bcd9-a9a5-4455-b2da-fed06051d502 | React
4ddfcfff-1072-4f58-b784-02d21962f405 | GraphQL
28be75b0-35cb-4e6b-ba7c-b7ecc9b17a99 | Flask
e0dd22e2-bb8d-42e9-a69c-9e16c587182f | Ruby
8747c553-8720-4c38-8008-1f935092819a | Rails
46db9c68-70f6-4e8f-b8fc-e2cf2b347cd5 | Serverless
f9680bf4-e54b-43a9-a7a8-fe795b4ce87b | AWS
ce9d8208-cb7c-4d1e-afe9-c7cda11afffe | SQL
dde07882-276f-4539-bdcc-e9b769455b78 | Postgres
4200aed9-f773-4cee-ac5a-301dc7a646e7 | Frameworks
0d325a30-7262-4914-90fe-6c90ac725fc2 | FrontEnd
a442f459-74bf-4206-addc-432680f11c44 | Redux
e02e9635-be20-4063-9baa-46af17e33811 | .NET
48c0e583-9fed-49a1-b1a3-0f2daea4fa97 | Algorithms
cd8f53dd-baa4-43b5-a869-1fc1541c67ec | CS
7ac87ffc-051d-46f8-8f9c-cc4fd8a4df74 | Career
faf79c64-7722-4b00-84c0-a805cf3f4b16 | Interviews
3e73c86f-fadf-48fb-ae1e-6b847e3934eb | Angular
96c2e86f-af02-44fb-ba80-4480efc95324 | TypeScript
c0f3c83d-bb25-4746-ad44-0fbb9a660e17 | Podcast
ba7b7dbb-d082-4ff0-905e-522b30aaec2c | BackEnd
b864f017-91de-48f6-a02b-b903abe4ecb3 | Databases
75af4e8f-6bdf-486e-97cd-13e8d434e398 | Docker
c0142708-7ead-4bbd-b12a-7581a1056317 | Swagger
30ab42c3-ced3-443b-ac41-332ec3d1dc60 | Postman
2b6f204d-0338-41ca-a82a-5c3c759ff510 | Tools
43c5b3e0-7eb6-405b-9db2-7540fba679d5 | apis
8cef0a7e-63b4-4dbf-b942-1f8355c8ab45 | Data Science
86a8f01e-3390-41c7-a23a-7d603815ec02 | Design
6f45bbb4-f78c-4a81-9b50-210fe6c5ad27 | Ethics in CS
5519988f-bebd-46c3-9d9b-4e02642faddc | Code Reviews
2bf14dc6-a66c-4ff1-b75d-4d1051e1242a | Functional Programming
44929775-9bb4-4840-af64-c6b0649d6677 | Elm
bff25abb-9589-45db-8113-c762a3966690 | Math
bb5a617c-0a92-48c7-a786-de89b7ace93a | Automation
0ed56654-4752-4d35-aa8e-25ee1fcfd24e | Security

**Comment by brylie** [comment]
I think we should let django-taggit take care of tags for us.

**Comment by BethanyG** [comment]
This is less about prototyping data and more about if we want to use a UUID as a `pk` for each tag - irrespective of weather or not we are using a tagging table or JSONB, and I parked them here so that they wouldn't be buried inside a google sheet.

**Comment by brylie** [comment]
Makes sense. I can't think of a reason why UUID would be important for tags, as sequential keys should be fine. E.g. we are probably not concerned with people being able to guess an active tag ID and use via an API request, sense tags are a discoverability mechanism.

What is the reasoning for using UUID on the Resource model? Will we have hidden or private resources? Are we worried about web-scraping?

**Comment by BethanyG** [comment]
Closing this as no longer relevant.
