### ISSUE TITLE
Clean up "cbv3" Python environment from repository

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#26]
There is a folder in the repository root called "cbv3". It appears to be a local Python virtual environment. The virtual environment was likely checked in by accident, as it is unconventional to keep Python virtual environments under revision control.

## Task
- [x] Remove the "cbv3" Python environment from the repository

**Comment by BethanyG** [comment]
Going to take this.  This env is from @lpatmo, who checked it in by accident.  She's traveling atm and cannot make code commits.  This will be removed in the PR connected to `issue-24`.

**Comment by brylie** [comment]
I have already opened a pull request: #28

**Comment by BethanyG** [comment]
All yours then.  Please assign issue you are working on to yourself so everyone is (more or less) clear on who is up to what.

**Comment by brylie** [comment]
I can't self-assign, as I have not been added to this repository as a collaborator.

**Comment by lpatmo** [comment]
@brylie I will invite you to the org as a collaborator. Thanks for deleting those files! As I mentioned in the review, I meant to get to them earlier.
