### ISSUE TITLE
Add instructions to README for using Python virtual environment

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#27]
Related to #3 

The README currently says to run `pip install -r requirements.txt`. However, this by default will install all packages in the global Python namespace. It is more common to use a virtual environment to prevent package conflicts. Since we are not in consensus about using any higher-level Python dependency management library, let's just add instructions for using the default Python `venv` module.

## Task
- [ ] add instructions to README describing how to use the standard Python `venv` module to create a project virtual environment
- [ ] make sure common virtual environment paths (such as .venv) are added to .gitignore

**Comment by BethanyG** [comment]
Closing this as a full duplicate to issue-3. 

@brylie - if you have additional things to add related to #3, please do it there to avoid extra noise and confusion. We can edit the title of that issue for clarity, and add a checklist if you have concerns around specific items.  

We've had multiple slack and hangout discussions at this point around setup, and we don't have a single place where we've written out all of our notes and thoughts yet.  @RuubixO has expressed interest in writing up directions for new users, but has been time constrained with other commitments, and is also in active discussions in Slack around if we go to a fully dockerized dev setup for new contributors.  He (and we) need a little more time to really get clear on what "setup" works best.   

@lpatmo  -Could we consolidate all of these user setup issues under one umbrella and assign one or two people to organize as a mini-team?  I feel as though  we have multiple discussions and instructions going along this same line as well as multiple issues being opened.  I really want this to be clear and easy for newcomers, but we risk stalling progress on the app while we discuss documentation.

**Comment by brylie** [comment]
Ok. Issue #3 just doesn't have any description. I think it would be relatively easy to leave this issue open, as it is fairly specific and small in scope. The pull request that closes #3 can also close this issue, and we will be assured that the README contains instructions for creating a virtual environment.
