### ISSUE TITLE
Create instructions for new contributor expectations, requirements, environments, and setup.

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#3]

**Comment by brylie** [comment]
Some requirements may be missing, such as `vine`:

```
$ python manage.py migrate
...
ModuleNotFoundError: No module named 'vine'
```

**Comment by brylie** [comment]
It is not clear how to connect to the Postgres databse. What should the username and password be?

```py
DATABASES = {
    "default": env.db("DATABASE_URL", default="postgres:///cbv3_django_prototype")
}
```

**Comment by BethanyG** [comment]
Linking #12 and #13 here, as they apply to New user setup.

**Comment by brylie** [comment]
Since so many issues arebeing consolidated into this issue, it is increasingly important that we add a description and checklist with all of the desirrd elements to add to the README. That will help ensure that nothing falls through the cracks. I.e. please don't close an isdue without bringing over the contextual information.

In general, though, it is OK to have multiple small, focused issues to break down tasks into smaller chunks.

**Comment by brylie** [comment]
Also note that you didn't close #12 & #14 when linking them to this issue. Please re-open #27, since it is fairly descriptive.

**Comment by BethanyG** [comment]
Yeah. Agreed. This whole chain is now a mess.  I will open a meta-issue with a clear description, and re-link issues there and add a checklist.

**Comment by brylie** [comment]
K. We can also relax a bit on closing issues. There are less than 20 open issues for this project.

**Comment by lpatmo** [comment]
> it is increasingly important that we add a description and checklist with all of the desirerd elements to add to the README. 

Agreed -- I'm learning this too re: Jira tickets at work. We could adopt something like an `acceptance criteria` template. Will look into editing the issue templates next. Also, apologies for not writing a description on the original post here! Since this thread has gotten meta I'll close this and make sure another issue is clearly open re: setup instructions.

**Comment by bengineerdavis** [comment]
I would nominate this to be a reopened issue, so clarify how new contributions, and related issues. This comes specifically from doing setup. Centralizing this would allow people to work a bit more independently, and reduce maintainer load going forward, if this could be further clarified.
