### ISSUE TITLE
Add fixtures for quickly generating dummy content

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#34]
New developers will typically want some dummy content, so they can test API calls, etc. Django makes it fairly easy to [define project fixtures](https://docs.djangoproject.com/en/3.0/howto/initial-data/).

## Task
- [ ] Generate fixtures for existing project models

**Comment by BethanyG** [comment]
Already created through work on issue-20, issue-24, and others.  Will be in forthcoming PR request when tests on API endpoint have been added.

**Comment by brylie** [comment]
Ok. It might be reasonable to leave this issue open util there is a related pull request.
