### ISSUE TITLE
Allow developers to use local SQLite file instead of PostgreSQL

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#35]
Currently, Codebuddies README says it is necessary to install PostgreSQL in order to develop the project. This may prove as an unnecessary barrier to entry, particularly for the prototypal nature of the project in its current state. Until this project is more mature (and possibly deployed at some staging server), we should allow local development to proceed with a simple SQLite database.

## Task
- [ ] Create an optional environment variable approach to allow developers to use SQLite instead of PostgreSQL

**Comment by BethanyG** [comment]
Closing this as not fixing.  We have decided to use postgres, and we are moving toward having a setup that uses a dockerized dev setup.  We will be working toward deploying this on a staging server shortly, once @lpatmo  is back from traveling, and we've discussed the front end a little more.
