### ISSUE TITLE
`django-rest-framework-jwt` is Unmaintained as of 8/2019  Replace

### ISSUE THREAD

**Issue by BethanyG** [codebuddies/django-concept#39]
Since we followed a link from the DRF docs and a related tutorial directly to PyPI (where the status is not listed), we missed that https://github.com/jpadilla/django-rest-framework-jwt is **unmaintained** a of 8/2019.  See issue https://github.com/jpadilla/django-rest-framework-jwt/issues/484.  We will now need to replace it.

One recommended route is to ~~use https://github.com/davesque/django-rest-framework-simplejwt.  The two libraries look similar at first glance, so the hope is the replacement will be fairly straightforward.~~

**Using**: "drop-in fork" at https://github.com/Styria-Digital/django-rest-framework-jwt.

**Comment by BethanyG** [comment]
Thoughts on which way we'd like to go?  Should we use the drop-in replacement, or switch to the simplejwt lib?  Rude trick not making the status clear on PyPI.

**Comment by lpatmo** [comment]
Good catch! I vote to use the drop-in fork at https://github.com/Styria-Digital/django-rest-framework-jwt. :)

**Comment by BethanyG** [comment]
I think I am going to do just that....at least for now.
