### ISSUE TITLE
[Content] Update Django home page with some getting started tips

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#49]
## Context
@d3vild06 noted that the first screen users see after getting the dev environment set up (either with `docker-compose up`, which is being reviewed in the PR for #44 right now, or manually) is this:

![image](https://user-images.githubusercontent.com/4512699/72596881-791cde00-38c1-11ea-9a74-4fd33a960a93.png)

We could add some tips to that home page content to help contributors to the Django API about how to get started.

## Acceptance Criteria
(Coming soon as I figure this out too)
Initially: 
- http://127.0.0.1:8000/api/v1/resources/ #browse the API for resources
-  http://127.0.0.1:8000/admin #login using superuser credentials
- docker-compose run --rm manage createsuperuser # how to create a superuser
- docker-compose run --rm manage test # how to create a superuser
- docker-compose run --rm manage makemigrations # how to make migrations
- docker-compose run --rm manage migrate # how to migrate the migrations
- http://127.0.0.1:8000/auth/obtain_token/ #get a token
- http://127.0.0.1:8000/auth/users/ #create a user

**Comment by sebbel** [comment]
I'm taking this

**Comment by sebbel** [comment]
https://github.com/codebuddies/django-concept/pull/54 here is the PR
