### ISSUE TITLE
ModuleNotFoundError: No module named 'vine'

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#5]
When trying to run initial migrations, I get the following error:

```
ModuleNotFoundError: No module named 'vine'
```

This may be related to a pinned dependency version for celery < 5.0:

https://github.com/celery/celery/issues/3547

**Comment by brylie** [comment]
It may be good to unpin these versions, or at least use Pipenv to manage the dependency lockfile.

**Comment by BethanyG** [comment]
This was an oversight by Linda and myself.  We intended to remove celery until we were further along, but then created issues when we didn't remove all the dependancies.  The requirements.txt file as now been updated with the original dependancies, so I am going to close this for now.  I will take a look at the pinned versions to make sure we have a reasonable minimum.
