### ISSUE TITLE
Relocate the Postgres container volume so it is no longer versioned

### ISSUE THREAD

**Issue by bengineerdavis** [codebuddies/django-concept#52]
# Actions

- [x] ~~Confirm that repo size reduces with by adding `db_data` to `.gitignore` file.~~ gitignore already ignores db_data

- [x] Confirm that leaving the volume undefined in `docker-compose.yaml` doesn't produce any side effects and maintains the functionality of the app.

- [ ] Seek more feedback on whether to continue pursuing this issue.

# Notes

- When running git rm --cached db_data I get:

> fatal: pathspec 'db_data' did not match any files

After eliminating local Postgres volume, current repo size seems primarily derived from these directories within the django project directory:
`./resources` `./users` `./templates`

# Overview
Over on slack, we noticed that the current repo is about 73mb, which seems considerably larger than the amount of data we've put into the app.

## Steps
1. I first searched for `venv` in `.git`, which didn't return anything.

2. Then I searched recursively for the largest sized directories/files in our repo and with `sudo ls -lR | sudo du -ah | sort -n -r | head -n 30`

The results:

> 964K	./cbv3_django_prototype
736K	./.git/objects/pack/pack-af3bbc530aded22c05b12ddc6bd8e00d44bef547.idx
680K	./cbv3_django_prototype/cbv3_django_prototype
608K	./db_data/base/16384/1255
608K	./db_data/base/13117/1255
608K	./db_data/base/13116/1255
608K	./db_data/base/1/1255
584K	./db_data/global
496K	./db_data/base/16384/1249
472K	./db_data/base/16384/2608
448K	./db_data/base/13117/2608
448K	./db_data/base/13116/2608
448K	./db_data/base/1/2608
408K	./db_data/base/16384/2838
408K	./db_data/base/13117/2838
408K	./db_data/base/13116/2838
408K	./db_data/base/1/2838
400K	./db_data/base/16384/2674
392K	./db_data/base/13117/1249
392K	./db_data/base/13116/1249
392K	./db_data/base/1/1249
368K	./db_data/base/13117/2674
368K	./db_data/base/13116/2674
368K	./db_data/base/1/2674
360K	./db_data/base/16384/2673
328K	./db_data/base/16384/2609
328K	./db_data/base/13117/2673
328K	./db_data/base/13117/2609
328K	./db_data/base/13116/2673
328K	./db_data/base/13116/2609

I had to run `sudo` because db_data is the local volume associated with our **`db`** Postgres container, which will always made modifications to files with privileged access. I spoke with @BethanyG and @angelocordon, and we agreed that this volume should never be in the git-versioned files. 

## Machine
Fedora 30 (Linux)

# Options
## .gitignore `da_data`
However, this is more of a bandaid, since the volume is still in the project directory.

## Let `docker-compose` abstract the local volume setup
This will make access to the volume files trickier, but can remove a manual config step that we might not need to worry about anyway.

**Comment by bengineerdavis** [comment]
Currently, `.git` isn't tracking `db_data` volume. I'll have to dig some more to determine what is causing the repo size.

**Comment by billglover** [comment]
This has puzzled me for a while. I couldn't find a copy of `db_data` within the repo. It did (for a while) exist in the project folder, but didn't make it into the project history.

When you run the following command (I removed `sudo`):

```plain
ls -lR | du -ah | sort -n -r | head -n 30
```

This returns the largest directories in the project folder. It doesn't take into account whether or not these files are part of the git repository.

The commands in issue #53 remove unnecessary files in the project history. Running them reveals that the large repository size appears to have come from the inadvertent inclusion of a python virtual environment in the project repository.

@bengineerdavis I propose closing this issue and using #53 to address the large repository size.

**Comment by bengineerdavis** [comment]
Thanks for closing this. And I realized that, too, but should've followed
up here.
