### ISSUE TITLE
[Cleanup]  Reduce repo size by cleaning up the .git folder

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#53]
## Context
We have some artifacts left over in the .git folder that we can clean up to reduce the size of the project from ~70mb to 384K. There was some discussion on Slack about this recently.

## Acceptance Criteria 
- Tackle after #44 
- h/t @sunu for these findings:

```
$ du -sh .git                             
71M	.git
$ git filter-branch --index-filter 'git rm -r --cached --ignore-unmatch cbv3' --prune-empty -- --all
...
$ git for-each-ref --format="delete %(refname)" refs/original | git update-ref --stdin
$ git reflog expire --expire=now --all
$ git gc --prune=now
$ du -sh .git                                                                         
384K	.git
```
- Reduced the size of .git folder from 71M to 384K 

https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by billglover** [comment]
I've run this against my fork without issue. But we'll need to do this against this repo before it takes effect. As it involves a `--force` push it would be good to close down open PRs first. I'm happy to pick this up as soon as #54 is merged.

@sebbel you may want to bring your fork into line once this is complete.

**Comment by billglover** [comment]
Running this against master reduces repo size from 81M to 344K. @lpatmo and @BethanyG, as you both have open branches/forks that have active development, I'll wait for you both to give me the nod to push this and rewrite history.

**Comment by lpatmo** [comment]
Thanks Bill! I'm all good here! (I need to delete my old branches... sorry
about that) Not sure if Bethany would prefer that this waits until after
#43 to reduce potential conflicts in her branch.

**Comment by billglover** [comment]
I propose pushing this today so that we can free up further contribution. @BethanyG any objections?

**Comment by BethanyG** [comment]
None at all!  Don't think this would create any issues, and would certainly help slim things down considerably.

**Comment by billglover** [comment]
@lpatmo, this is done but your [linda-drf](https://github.com/codebuddies/django-concept/tree/linda-drf) branch still has the virtual environment in it and so a clone of the repo is still 81M.

Do you need this branch? If not, I'll remove it and close this issue. If you do need it, I propose re-purposing the hangout tomorrow to work through rebasing any changes.

**Comment by lpatmo** [comment]
I don't need that branch anymore, so it's fine to remove it. Thanks Bill!

**Comment by billglover** [comment]
All branches removed. Repo size now much smaller.

```plain
du -sh ./
932K
```

**Note:** anyone who wants to merge changes should look to rebase instead of merge. I would recommend everyone who has a fork of this repo to consider re-forking.
