### ISSUE TITLE
[enhancement] use GitHub actions to run tests on PRs

### ISSUE THREAD

**Issue by billglover** [codebuddies/django-concept#56]
GitHub Actions provides the ability to automate development workflows including: linting, building, testing, releasing and deploying. Automation of these tasks helps reduce the workload for maintainers, but also helps ensure some consistency to workflows. It can also provide a degree of confidence to contributors that their changes won't have unintended consequences.

This issue is to set up GitHub Actions to execute tests for PRs raised by contributors.

## Acceptance Criteria

* [x] GitHub Action workflow is triggered when a new PR is raised
* [x] The workflow executes `manage.py test` against the PR commit
* [x]  The results of tests are visible to both contributor and maintainer

**Comment by billglover** [comment]
I have an initial version of this running and it appears to work.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/94501/73545633-9d38fd00-4433-11ea-9bb6-c277a3876c85.png">

Would anyone be able to guide me through writing a failing test so that I can demonstrate what happens when tests fail?

**Comment by billglover** [comment]
Looks like this is now working as expected.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/94501/73552753-b5634900-4440-11ea-9e2b-6c00f7ef7a47.png">

**Comment by sebbel** [comment]
I love github actions, that's a darn good proposal @billglover :clap:

**Comment by lpatmo** [comment]
😍😍😍
