### ISSUE TITLE
Initial Resources model and admin form

### ISSUE THREAD

**Issue by brylie** [codebuddies/django-concept#6]
Create the initial Resource model and register it with the Django Admin.

**Comment by BethanyG** [comment]
Closing this as superseded by #8.

**Comment by brylie** [comment]
Ah, this issue will actually be *closed* by #8, and might remain open until #8 is merged.

The issue can automatically be closed by using GitHub issue keywords:
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by brylie** [comment]
E.g. just add `Closes #6` in the pull request description.
